학습목표

지난 시간에 이어서 텐서 조작(Tensor Manipulation)에 대해 계속 알아본다.\
핵심키워드

* 텐서(Tensor)
* 넘파이(NumPy)
* 텐서 조작(Tensor Manipulation)
* View, Squeeze, Unsqueeze, Type Casting, Concatenate, Stacking, In-place Operation

In [3]:
import numpy as np
import torch

## View(Reshape)

In [6]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

torch의 view는 numpy에서의 reshape와 같은 역할을 한다.

In [7]:
print(ft.view(-1, 3))  # -1로 표시한 부분의 차원은 모르겠고, 나머지 값을 토대로 모양 바꿔주기
print(ft.view(-1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [10]:
print(ft.view(-1, 1, 3)) # -1은 가장 특정하기 힘든(변동이 심한) 차원 부분에다 적어 줌
print(ft.view(-1, 1, 3).shape)
print(ft.view(4, 1, 3))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])


## Squeeze
1의 값을 가지는 dimension을 쥐어짜서 없애준다.

In [16]:
tf = torch.FloatTensor([[0], [1], [2]])
print(tf)
tf.shape

tensor([[0.],
        [1.],
        [2.]])


torch.Size([3, 1])

In [15]:
print(tf.squeeze())
print(tf.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [17]:
tf.squeeze(dim = 0)

tensor([[0.],
        [1.],
        [2.]])

dim = 0 값은 3이므로 squeeze로 인한 변화 없음

In [19]:
tf.squeeze(dim = 1)

tensor([0., 1., 2.])

dim = 1 의 값이 1이므로 squeeze로 인해 해당 dim 사라짐

## Unsqueeze
Squeeze의 반대 기능: dim

In [21]:
ft = torch.Tensor([1,2,3])
print(ft.shape)

torch.Size([3])


In [36]:
print(ft.unsqueeze(dim= 0))
#view로 바로 위의 코드 역할 똑같이 하도록 구현
print(ft.view(1, -1)) # dim = 0에서의 element개수가 1만 되면 되는 것이므로
print(ft.view(1, -1).shape)

tensor([[1., 2., 3.]])
tensor([[1., 2., 3.]])
torch.Size([1, 3])


In [23]:
print(ft.unsqueeze(1)) # dim = 1의 자리가 1되도록. 그러면 1*3이었던 ft가 3*1이 되겠지

tensor([[1.],
        [2.],
        [3.]])


In [28]:
print(ft.unsqueeze(dim = -1)) # 가장 뒤 차원보다 한 차원 더 뒤의 값이 1이 되도록
print(ft.unsqueeze(-1).shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


## Type Casting
Tensor의 type을 바꾸어 준다.

In [29]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [33]:
print(lt.float())
print(lt.float().shape)

tensor([1., 2., 3., 4.])
torch.Size([4])


언제는 스칼라로 취급되고 언제 n*1의 벡터로 취급되는지 그 기준을 잘 모르겠다.

In [37]:
bt = torch.ByteTensor([True, False, False, True])  # ByteTensor의 경우 불린 값을 저장
bt

tensor([1, 0, 0, 1], dtype=torch.uint8)

In [44]:
# ByteTensor의 예시
bt = lt==3
print(bt)

tensor([False, False,  True, False])


In [45]:
print(bt.long())
print(bt.float())

tensor([0, 0, 1, 0])
tensor([0., 0., 1., 0.])


## Concatenate

In [49]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

print(torch.cat([x,y], dim = 0)) # concatenate 하고자 하는 두 요소는 리스트로 묶어서 입력
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking
Tensor의 shape가 같다면 Tensor을 그대로 앞으로 쌓거나 눕혀서 옆으로 쌓는다 

In [50]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [53]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [54]:
torch.stack([x,y,z], dim = 1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [55]:
# stack매서드를 concatenate로 구현하기
torch.cat([x.unsqueeze(dim = 0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

## Ones and Zeros

In [56]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
print(torch.ones_like(x))  # x와 똑같은 shape의 1로 가득찬 tensor만들기
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


cpu tensor와 gpu tensor간에는 연산이 안된다.\
같은 device에 있어야 연산 가능.\
이렇듯 같은 device에 tensor들을 선언해 줄 때, ones_like(), zeros_like()매서드가 활용되게 된다.

## In-place Operation
list의 immutability와 유사

In [58]:
x = torch.FloatTensor([[1,2], [3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.))  # 연산 결과를 가지고 연산 당하는 원래 객체의 값을 대체
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
