https://www.boostcourse.org/ai214/lecture/42282/?isDesc=false

학습목표

텐서 조작(Tensor Manipulation)에 대해 알아본다.
핵심키워드

* 텐서(Tensor)
* 넘파이(NumPy)
* 텐서 조작(Tensor Manipulation)
* 브로드캐스팅(Broadcasting)

In [6]:
import numpy as np
import torch

# Numpy Review

1D Array w/ Numpy

In [7]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [9]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Elements
print('t[2:5] t[4:-1]j = ', t[2:5], t[4:-1]) # Slicings
print('t[:2] t[3:]     = ', t[:2], t[3:]) # Slicings

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]j =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


2D Array w/ Numpy

In [11]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [12]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


In [26]:
print(t[:,1])  # Numpy, Tensor에서는 Slicing할 때 행, 열 인덱스를 한 리스트 안에 담는다!

tensor([ 2.,  5.,  8., 11.])


# Pytorch Tensor

1D Array w/ Pytorch

In [13]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [15]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])  # Slicing
print(t[:2], t[3:])  # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


2D Array w/ Pytorch

In [19]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [27]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


---

Pytorch에서 지원하는 연산 방법들

# Broadcasting

In [29]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[3, 2]])
m1 + m2

tensor([[6., 5.]])

In [30]:
# Vector + Scaler
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])  # 3 -> [[3, 3]]
m1 + m2

tensor([[4., 5.]])

In [31]:
# 2*1 Vector + 1*2 Vector
m1 = torch.FloatTensor([[1],[2]])
m2 = torch.FloatTensor([[3, 4]])
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

Matrix multiplication vs Multiplication

In [34]:
print()
print('-----------')
print('Matmul vs Mul')
print('-----------')
m1 = torch.FloatTensor([[1,2], [3, 4]])  # 2*2
m2 = torch.FloatTensor([[2], [3]])  # 2*1
print(m1.matmul(m2))  # 행렬곱(matrix multiply)
# 행렬의 (일반)곱 - 같의 자리의 element끼리의 곱
print(m1*m2)
print(m1.mul(m2)) # mul = '*'


-----------
Matmul vs Mul
-----------
tensor([[ 8.],
        [18.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


matmul(matrix multiply)와 mul(multiply)의 경우 곱하고자 하는 두 수 중 한 수 뒤에 .matmul()이나 .mul()식의 매서드로 붙어서 활용된다.

Mean

In [35]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [38]:
# Can't use mean on integers
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use t.mean for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [41]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


Sum

In [44]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


Max & Argmax

In [45]:
t = torch.FloatTensor([[1,2], [3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

The max operator returns one value if it is called without an argument.

In [46]:
t.max()

tensor(4.)

The max operator returns two values when called with dimention specified. The first value is the maximum value, and the second value is the argmax: the indice of the element with maximum value.

In [48]:
t.max(dim = 0) # Returns two values: Max and Argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [49]:
print('Max: ', t.max(dim = 0)[0])

Max :  tensor([3., 4.])


In [50]:
print('Argmax: ', t.max(dim = 0)[1])

Argmax:  tensor([1, 1])


In [51]:
t.max(dim = 1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

In [52]:
t.max(dim = -1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))